### ISSUE TITLE
[BUG]Market Error

### ISSUE THREAD

**Issue by ADMTec** [pulseP1986/free-mu-cms#14]
Warehouse option displays the message "Please Logout from game" but the character is not logged in

1. Go to Market
2. Click on Warehouse
3. See error

![Captura de Tela (103)](https://github.com/pulseP1986/free-mu-cms/assets/16466549/d6b26092-6215-41d4-bb1a-dd8faa5171cd)

**Comment by pulseP1986** [comment]
Some issue in your database
