### ISSUE TITLE
item_upgrade.ejs Missing

### ISSUE THREAD

**Issue by klister803** [pulseP1986/free-mu-cms#2]
ejs_template file item_upgrade.ejs is missing

without it the workshop won't show this 

![image](https://github.com/pulseP1986/free-mu-cms/assets/35279034/80d608a1-fe04-42d8-830a-74c2543b466d)

**Comment by pulseP1986** [comment]
https://github.com/pulseP1986/free-mu-cms/commit/52ea5af9a89b8202ad98d093e657a047874bca56
