### ISSUE TITLE
[BUG] Referral system function parameters

### ISSUE THREAD

**Issue by Mrc-Junior** [pulseP1986/free-mu-cms#24]
**Describe the bug**
Go to admincp active the referral syste, and try invite players use this.
You have an issue on :  
**model.account.php**
`        public function check_if_reward_was_claimed($curUser, $id, $server, $account){
            $stmt = $this->website->db('web')->prepare('SELECT TOP 1 id FROM DmN_Refferal_Claimed_Rewards WHERE reward_id = :id AND account = :account AND server = :server AND ref_account = :ref_account');
            $stmt->execute([':id' => $id, ':account' => $curUser, ':server' => $server, ':ref_account' => $account]);
            return $stmt->fetch();
        }`

This function have 4 parameters, but on the theme you write only 3 then this cause issue for use the system
On theme file:
`if($this->Maccount->check_claimed_referral_rewards($value['id'], $char['Name'], $value['server']) != false)`

You can fix this ! :)

**Comment by Mrc-Junior** [comment]
@pulseP1986 When you make new release ?
If need help for the system I avaible also :)

**Comment by pulseP1986** [comment]
if($this->Maccount->check_claimed_referral_rewards($this->session->userdata(['user' => 'username']), $value['id'], $char['Name'], $value['server']) != false) fix in your template if you need
