### ISSUE TITLE
[BUG] Latest Version its not working correctly.

### ISSUE THREAD

**Issue by klister803** [pulseP1986/free-mu-cms#3]
Using the latest changes to the code does not allow you see accounts in admin cp, install plugins, and there are probably a few more bugs that i have forgot

My guess is because of the code refactor , but i might be wrong

**Comment by pulseP1986** [comment]
Provide logs from application/logs/tracy folder and point out exact version what you are using.

**Comment by klister803** [comment]
Php version 8.1 
Version 1.2.4.6
No logs are created about the plugin install issue



The logs from the account section are

02-23-2024 05:47:21.363200 #### SELECT TOP 10 m.memb_guid, m.memb___id, m.appl_days, m.dmn_country, m.activated,  d.viptime FROM MEMB_INFO AS m LEFT JOIN [dmncms].dbo.DmN_Vip_Users AS d ON(m.memb___id Collate Database_Default = d.memb___id Collate Database_Default) WHERE memb_guid NOT IN (SELECT Top '0' memb_guid FROM MEMB_INFO  ORDER BY m.appl_days DESC)  ORDER BY m.appl_days DESC
================================================================================
02-23-2024 05:47:21.363800 #### PDOException: SQLSTATE[HY000]: General error: 20018 Incorrect syntax near '0'. [20018] (severity 15) [SELECT TOP 10 m.memb_guid, m.memb___id, m.appl_days, m.dmn_country, m.activated,  d.viptime FROM MEMB_INFO AS m LEFT JOIN [dmncms].dbo.DmN_Vip_Users AS d ON(m.memb___id Collate Database_Default = d.memb___id Collate Database_Default) WHERE memb_guid NOT IN (SELECT Top '0' memb_guid FROM MEMB_INFO  ORDER BY m.appl_days DESC)  ORDER BY m.appl_days DESC] in /home/cmsdmns/application/libraries/lib.db.php:110
Stack trace:

**Comment by pulseP1986** [comment]
Fixed in v1.2.4.7
