### ISSUE TITLE
[BUG] Issue with account section in Admin CP

### ISSUE THREAD

**Issue by klister803** [pulseP1986/free-mu-cms#5]
Issue with accounts in admincp persists 
Website version: 1.2.4.8 
PHP Version: 8.1
SQL : 2017

02-23-2024 17:06:45.297200 #### SELECT TOP 10 m.memb_guid, m.memb___id, m.appl_days, m.dmn_country, m.activated,  d.viptime FROM MEMB_INFO AS m LEFT JOIN [dmncms].dbo.DmN_Vip_Users AS d ON(m.memb___id Collate Database_Default = d.memb___id Collate Database_Default) WHERE memb_guid NOT IN (SELECT Top '0' memb_guid FROM MEMB_INFO  ORDER BY m.appl_days DESC)  ORDER BY m.appl_days DESC
================================================================================
02-23-2024 17:06:45.297700 #### PDOException: SQLSTATE[HY000]: General error: 20018 Incorrect syntax near '0'. [20018] (severity 15) [SELECT TOP 10 m.memb_guid, m.memb___id, m.appl_days, m.dmn_country, m.activated,  d.viptime FROM MEMB_INFO AS m LEFT JOIN [dmncms].dbo.DmN_Vip_Users AS d ON(m.memb___id Collate Database_Default = d.memb___id Collate Database_Default) WHERE memb_guid NOT IN (SELECT Top '0' memb_guid FROM MEMB_INFO  ORDER BY m.appl_days DESC)  ORDER BY m.appl_days DESC] in /home/dmncms/application/libraries/lib.db.php:110
Stack trace:

**Comment by pulseP1986** [comment]
https://github.com/pulseP1986/free-mu-cms/commit/df9247b6d3d88217ed5bccf38991d726045b363a
