### ISSUE TITLE
[BUG] Setting Laguague does not work

### ISSUE THREAD

**Issue by klister803** [pulseP1986/free-mu-cms#6]
Version : 1.2.4.8
Bug: Setting any languague as default or even clicking on the icon to change the languague it bugs out.
This happens with any of these buttons here 
![image](https://github.com/pulseP1986/free-mu-cms/assets/35279034/ade26bd6-ce16-48cc-ba21-752332d22f0a)

Call to undefined method website::c()
![image](https://github.com/pulseP1986/free-mu-cms/assets/35279034/96ad9d8b-0c48-4bdf-a4c9-aa9e096cda80)

**Comment by ADMTec** [comment]
the same to me

**Comment by pulseP1986** [comment]
https://github.com/pulseP1986/free-mu-cms/blob/1.2.3/application/controllers/controller.admincp.php
